In [26]:
import pandas as pd
import numpy as np

df = pd.read_excel("/kaggle/input/datasets/karvysingh/dalisa/FCC_feed_data.xlsx",
                   sheet_name="Feed Data")

# remove the units row
df = df[pd.to_numeric(df["Sample No."], errors="coerce").notna()].copy()

df["Sample No."] = df["Sample No."].astype(int)

for c in df.columns[1:]:
    df[c] = pd.to_numeric(df[c])

df.head()

,Sample No.,Sp. Gr,CCR,T.S,T.N,IBP,5 %,10 %,30 %,50 %,70 %,90 %,95 %,FBP,P,N,A
1,1,0.9245,0.40,2.93,1401,37,317,342,392,423,454,498,514,538,8.3,24.1,67.6
2,2,0.9960,1.55,4.35,200,42,409,428,458,477,494,514,523,537,7.8,25.3,66.8
3,3,0.8683,0.04,0.03,22,103,224,263,337,380,420,473,497,536,15.2,45.0,39.8
4,4,0.9136,0.04,1.54,329,111,276,318,368,391,407,427,436,460,14.8,15.5,70.5
5,5,0.9303,0.28,3.06,1161,169,257,320,402,438,474,519,535,574,11.2,23.3,65.6

In [27]:
features = [
    "Sp. Gr",
    "5 %",
    "10 %",
    "30 %",
    "50 %",
    "70 %",
    "90 %",
    "95 %"
]

targets = ["P", "N", "A"]

train = df[df["Sample No."].between(1, 16)].copy()
test  = df[df["Sample No."].between(23, 28)].copy()
val   = df[df["Sample No."].between(17, 22)].copy()

X_train = train[features]
y_train = train[targets]

X_test = test[features]
y_test = test[targets]

X_val = val[features]
y_val = val[targets]

In [28]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(-1, 1))

X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)
X_val   = scaler.transform(X_val)

In [29]:
import torch
import torch.nn as nn

from torch.func import functional_call
from torch.nn.utils import parameters_to_vector, vector_to_parameters
from torch.utils.data import TensorDataset, DataLoader

class ANN(nn.Module):
    def __init__(self, h1, h2):
        super().__init__()

        self.fc1 = nn.Linear(8, h1)
        self.fc2 = nn.Linear(h1, h2)
        self.out = nn.Linear(h2, 1)

    def forward(self, x):
        x = torch.tanh(self.fc1(x))       # tansig
        x = torch.sigmoid(self.fc2(x))    # logsig
        return self.out(x)                # purelin

In [30]:
DTYPE = torch.float64

Xtr = torch.tensor(X_train, dtype=DTYPE)
Xte = torch.tensor(X_test, dtype=DTYPE)
Xv  = torch.tensor(X_val, dtype=DTYPE)

In [31]:
!pip install -q torch-levenberg-marquardt
import torch_levenberg_marquardt as tlm

In [32]:
def train_lm(y, h1, h2, seed=42, epochs=100):

    torch.manual_seed(seed)

    model = ANN(h1, h2).double()

    y_tensor = torch.tensor(
        np.asarray(y),
        dtype=torch.float64
    ).reshape(-1, 1)

    dataset = TensorDataset(
        Xtr,
        y_tensor
    )

    loader = DataLoader(
        dataset,
        batch_size=len(dataset),
        shuffle=False
    )

    lm = tlm.training.LevenbergMarquardtModule(
        model=model,
        loss_fn=tlm.loss.MSELoss(),
        learning_rate=1.0,
        attempts_per_step=10,
        solve_method="qr",
    )

    tlm.utils.fit(
        lm,
        loader,
        epochs=epochs,
    )

    return model

In [33]:
model_P = train_lm(
    y_train["P"],
    12, 13,
    seed=42
)

model_N = train_lm(
    y_train["N"],
    12, 12,
    seed=43
)

model_A = train_lm(
    y_train["A"],
    9, 9,
    seed=44
)

Epoch 1/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 1/100: 100%|██████████| 1/1 [00:00<00:00,  4.80it/s]
Epoch 1/100: 100%|██████████| 1/1 [00:00<00:00,  4.80it/s, loss=1.0877e+02, damping=1.0000e-03, attempts=2]
Epoch 1/100: 100%|██████████| 1/1 [00:00<00:00,  4.80it/s, epoch_avg_loss=1.0877e+02]

Epoch 2/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 2/100: 100%|██████████| 1/1 [00:00<00:00, 137.10it/s, loss=6.0612e+01, damping=1.0000e-01, attempts=4]
Epoch 2/100: 100%|██████████| 1/1 [00:00<00:00, 100.05it/s, epoch_avg_loss=6.0612e+01]

Epoch 3/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 3/100: 100%|██████████| 1/1 [00:00<00:00, 159.64it/s, loss=4.6115e+01, damping=1.0000e-01, attempts=2]
Epoch 3/100: 100%|██████████| 1/1 [00:00<00:00, 123.35it/s, epoch_avg_loss=4.6115e+01]

Epoch 4/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 4/100: 100%|██████████| 1/1 [00:00<00:00, 164.52it/s, loss=3.9129e+01, damping=1.0000e-01, attempts=2]
Epoch 4/100: 100%|██████████| 1/1 [00:00<00:00, 125.74it/s, epoch_avg_loss=3.9129e+01]

Epoch 5/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 5/100: 100%|██████████| 1/1 [00:00<00:00, 166.86it/s, loss=2.8554e+01, damping=1.0000e+00, attempts=3]
Epoch 5/100: 100%|██████████| 1/1 [00:00<00:00, 128.97it/s, epoch_avg_loss=2.8554e+01]

Epoch 6/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 6/100: 100%|██████████| 1/1 [00:00<00:00, 161.31it/s, loss=2.0914e+01, damping=1.0000e-01, attempts=1]
Epoch 6/100: 100%|██████████| 1/1 [00:00<00:00, 120.56it/s, epoch_avg_loss=2.0914e+01]

Epoch 7/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 7/100: 100%|██████████| 1/1 [00:00<00:00, 109.39it/s, loss=1.8341e+01, damping=1.0000e+00, attempts=3]
Epoch 7/100: 100%|██████████| 1/1 [00:00<00:00, 88.05it/s, epoch_avg_loss=1.8341e+01]

Epoch 8/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 8/100: 100%|██████████| 1/1 [00:00<00:00, 208.90it/s, loss=1.4612e+01, damping=1.0000e-01, attempts=1]
Epoch 8/100: 100%|██████████| 1/1 [00:00<00:00, 150.26it/s, epoch_avg_loss=1.4612e+01]

Epoch 9/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 9/100: 100%|██████████| 1/1 [00:00<00:00, 160.29it/s, loss=1.1483e+01, damping=1.0000e+00, attempts=3]
Epoch 9/100: 100%|██████████| 1/1 [00:00<00:00, 113.01it/s, epoch_avg_loss=1.1483e+01]

Epoch 10/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 10/100: 100%|██████████| 1/1 [00:00<00:00, 197.91it/s, loss=6.8238e+00, damping=1.0000e-01, attempts=1]
Epoch 10/100: 100%|██████████| 1/1 [00:00<00:00, 137.71it/s, epoch_avg_loss=6.8238e+00]

Epoch 11/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 11/100: 100%|██████████| 1/1 [00:00<00:00, 176.37it/s, loss=6.4793e+00, damping=1.0000e-01, attempts=2]
Epoch 11/100: 100%|██████████| 1/1 [00:00<00:00, 126.40it/s, epoch_avg_loss=6.4793e+00]

Epoch 12/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 12/100: 100%|██████████| 1/1 [00:00<00:00, 216.66it/s, loss=1.0462e+00, damping=1.0000e-02, attempts=1]
Epoch 12/100: 100%|██████████| 1/1 [00:00<00:00, 144.08it/s, epoch_avg_loss=1.0462e+00]

Epoch 13/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 13/100: 100%|██████████| 1/1 [00:00<00:00, 194.37it/s, loss=1.9600e-01, damping=1.0000e-03, attempts=1]
Epoch 13/100: 100%|██████████| 1/1 [00:00<00:00, 139.04it/s, epoch_avg_loss=1.9600e-01]

Epoch 14/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 14/100: 100%|██████████| 1/1 [00:00<00:00, 178.38it/s, loss=1.1466e-02, damping=1.0000e-04, attempts=1]
Epoch 14/100: 100%|██████████| 1/1 [00:00<00:00, 125.29it/s, epoch_avg_loss=1.1466e-02]

Epoch 15/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 15/100: 100%|██████████| 1/1 [00:00<00:00, 192.89it/s, loss=1.4037e-03, damping=1.0000e-05, attempts=1]
Epoch 15/100: 100%|██████████| 1/1 [00:00<00:00, 125.75it/s, epoch_avg_loss=1.4037e-03]

Epoch 16/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 16/100: 100%|██████████| 1/1 [00:00<00:00, 191.14it/s, loss=3.2845e-07, damping=1.0000e-06, attempts=1]
Epoch 16/100: 100%|██████████| 1/1 [00:00<00:00, 124.62it/s, epoch_avg_loss=3.2845e-07]

Epoch 17/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 17/100: 100%|██████████| 1/1 [00:00<00:00, 180.77it/s, loss=1.0854e-14, damping=1.0000e-07, attempts=1]
Epoch 17/100: 100%|██████████| 1/1 [00:00<00:00, 130.79it/s, epoch_avg_loss=1.0854e-14]

Epoch 18/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 18/100: 100%|██████████| 1/1 [00:00<00:00, 188.65it/s, loss=4.4423e-29, damping=1.0000e-08, attempts=1]
Epoch 18/100: 100%|██████████| 1/1 [00:00<00:00, 134.67it/s, epoch_avg_loss=4.4423e-29]

Epoch 19/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 19/100: 100%|██████████| 1/1 [00:00<00:00, 188.29it/s, loss=2.2976e-29, damping=1.0000e-09, attempts=1]
Epoch 19/100: 100%|██████████| 1/1 [00:00<00:00, 133.84it/s, epoch_avg_loss=2.2976e-29]

Epoch 20/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 20/100: 100%|██████████| 1/1 [00:00<00:00, 193.66it/s, loss=1.1340e-29, damping=1.0000e-10, attempts=1]
Epoch 20/100: 100%|██████████| 1/1 [00:00<00:00, 125.68it/s, epoch_avg_loss=1.1340e-29]

Epoch 21/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 21/100: 100%|██████████| 1/1 [00:00<00:00, 180.04it/s, loss=7.0504e-30, damping=1.0000e-10, attempts=1]
Epoch 21/100: 100%|██████████| 1/1 [00:00<00:00, 115.32it/s, epoch_avg_loss=7.0504e-30]

Epoch 22/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 22/100: 100%|██████████| 1/1 [00:00<00:00, 105.14it/s, loss=5.0290e-30, damping=1.0000e-02, attempts=10]
Epoch 22/100: 100%|██████████| 1/1 [00:00<00:00, 85.49it/s, epoch_avg_loss=5.0290e-30]

Epoch 23/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 23/100: 100%|██████████| 1/1 [00:00<00:00, 108.70it/s, loss=5.0290e-30, damping=1.0000e+08, attempts=10]
Epoch 23/100: 100%|██████████| 1/1 [00:00<00:00, 91.13it/s, epoch_avg_loss=5.0290e-30]

Epoch 24/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 24/100: 100%|██████████| 1/1 [00:00<00:00, 153.40it/s, loss=5.0290e-30, damping=1.0000e+10, attempts=3]
Epoch 24/100: 100%|██████████| 1/1 [00:00<00:00, 97.02it/s, epoch_avg_loss=5.0290e-30]

Training complete. Final epoch average loss: 5.0290e-30

Epoch 1/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 1/100: 100%|██████████| 1/1 [00:00<00:00, 180.87it/s, loss=3.4302e+02, damping=1.0000e-04, attempts=1]
Epoch 1/100: 100%|██████████| 1/1 [00:00<00:00, 122.69it/s, epoch_avg_loss=3.4302e+02]

Epoch 2/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 2/100: 100%|██████████| 1/1 [00:00<00:00, 181.41it/s, loss=1.4792e+02, damping=1.0000e-05, attempts=1]
Epoch 2/100: 100%|██████████| 1/1 [00:00<00:00, 115.82it/s, epoch_avg_loss=1.4792e+02]

Epoch 3/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 3/100: 100%|██████████| 1/1 [00:00<00:00, 140.50it/s, loss=1.3915e+02, damping=1.0000e-02, attempts=5]
Epoch 3/100: 100%|██████████| 1/1 [00:00<00:00, 107.84it/s, epoch_avg_loss=1.3915e+02]

Epoch 4/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 4/100: 100%|██████████| 1/1 [00:00<00:00, 151.35it/s, loss=4.8714e+01, damping=1.0000e-01, attempts=3]
Epoch 4/100: 100%|██████████| 1/1 [00:00<00:00, 113.46it/s, epoch_avg_loss=4.8714e+01]

Epoch 5/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 5/100: 100%|██████████| 1/1 [00:00<00:00, 172.76it/s, loss=2.8200e+01, damping=1.0000e-02, attempts=1]
Epoch 5/100: 100%|██████████| 1/1 [00:00<00:00, 128.40it/s, epoch_avg_loss=2.8200e+01]

Epoch 6/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 6/100: 100%|██████████| 1/1 [00:00<00:00, 185.33it/s, loss=1.0589e+01, damping=1.0000e-03, attempts=1]
Epoch 6/100: 100%|██████████| 1/1 [00:00<00:00, 132.55it/s, epoch_avg_loss=1.0589e+01]

Epoch 7/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 7/100: 100%|██████████| 1/1 [00:00<00:00, 170.58it/s, loss=2.6631e-01, damping=1.0000e-03, attempts=2]
Epoch 7/100: 100%|██████████| 1/1 [00:00<00:00, 124.94it/s, epoch_avg_loss=2.6631e-01]

Epoch 8/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 8/100: 100%|██████████| 1/1 [00:00<00:00, 165.21it/s, loss=1.2295e-01, damping=1.0000e-03, attempts=2]
Epoch 8/100: 100%|██████████| 1/1 [00:00<00:00, 123.53it/s, epoch_avg_loss=1.2295e-01]

Epoch 9/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 9/100: 100%|██████████| 1/1 [00:00<00:00, 184.87it/s, loss=1.8593e-04, damping=1.0000e-04, attempts=1]
Epoch 9/100: 100%|██████████| 1/1 [00:00<00:00, 133.57it/s, epoch_avg_loss=1.8593e-04]

Epoch 10/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 10/100: 100%|██████████| 1/1 [00:00<00:00, 197.47it/s, loss=1.2439e-09, damping=1.0000e-05, attempts=1]
Epoch 10/100: 100%|██████████| 1/1 [00:00<00:00, 138.11it/s, epoch_avg_loss=1.2439e-09]

Epoch 11/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 11/100: 100%|██████████| 1/1 [00:00<00:00, 159.68it/s, loss=1.2639e-19, damping=1.0000e-06, attempts=1]
Epoch 11/100: 100%|██████████| 1/1 [00:00<00:00, 120.24it/s, epoch_avg_loss=1.2639e-19]

Epoch 12/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 12/100: 100%|██████████| 1/1 [00:00<00:00, 190.14it/s, loss=1.0985e-28, damping=1.0000e-07, attempts=1]
Epoch 12/100: 100%|██████████| 1/1 [00:00<00:00, 124.46it/s, epoch_avg_loss=1.0985e-28]

Epoch 13/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 13/100: 100%|██████████| 1/1 [00:00<00:00, 190.72it/s, loss=6.4095e-29, damping=1.0000e-08, attempts=1]
Epoch 13/100: 100%|██████████| 1/1 [00:00<00:00, 139.58it/s, epoch_avg_loss=6.4095e-29]

Epoch 14/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 14/100: 100%|██████████| 1/1 [00:00<00:00, 186.48it/s, loss=6.0940e-29, damping=1.0000e-09, attempts=1]
Epoch 14/100: 100%|██████████| 1/1 [00:00<00:00, 128.09it/s, epoch_avg_loss=6.0940e-29]

Epoch 15/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 15/100: 100%|██████████| 1/1 [00:00<00:00, 189.83it/s, loss=4.4373e-29, damping=1.0000e-10, attempts=1]
Epoch 15/100: 100%|██████████| 1/1 [00:00<00:00, 136.39it/s, epoch_avg_loss=4.4373e-29]

Epoch 16/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 16/100: 100%|██████████| 1/1 [00:00<00:00, 97.54it/s, loss=4.4373e-29, damping=1.0000e+00, attempts=10]
Epoch 16/100: 100%|██████████| 1/1 [00:00<00:00, 82.26it/s, epoch_avg_loss=4.4373e-29]

Epoch 17/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 17/100: 100%|██████████| 1/1 [00:00<00:00, 102.14it/s, loss=3.4907e-29, damping=1.0000e+10, attempts=10]
Epoch 17/100: 100%|██████████| 1/1 [00:00<00:00, 77.23it/s, epoch_avg_loss=3.4907e-29]

Training complete. Final epoch average loss: 3.4907e-29

Epoch 1/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 1/100: 100%|██████████| 1/1 [00:00<00:00, 162.12it/s, loss=6.1591e+02, damping=1.0000e-03, attempts=2]
Epoch 1/100: 100%|██████████| 1/1 [00:00<00:00, 107.38it/s, epoch_avg_loss=6.1591e+02]

Epoch 2/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 2/100: 100%|██████████| 1/1 [00:00<00:00, 153.64it/s, loss=5.8583e+02, damping=1.0000e-04, attempts=1]
Epoch 2/100: 100%|██████████| 1/1 [00:00<00:00, 113.40it/s, epoch_avg_loss=5.8583e+02]

Epoch 3/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 3/100: 100%|██████████| 1/1 [00:00<00:00, 172.01it/s, loss=4.4985e+02, damping=1.0000e-05, attempts=1]
Epoch 3/100: 100%|██████████| 1/1 [00:00<00:00, 120.70it/s, epoch_avg_loss=4.4985e+02]

Epoch 4/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 4/100: 100%|██████████| 1/1 [00:00<00:00, 155.93it/s, loss=1.6333e+02, damping=1.0000e-04, attempts=3]
Epoch 4/100: 100%|██████████| 1/1 [00:00<00:00, 119.51it/s, epoch_avg_loss=1.6333e+02]

Epoch 5/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 5/100: 100%|██████████| 1/1 [00:00<00:00, 185.98it/s, loss=1.3573e+02, damping=1.0000e-05, attempts=1]
Epoch 5/100: 100%|██████████| 1/1 [00:00<00:00, 141.79it/s, epoch_avg_loss=1.3573e+02]

Epoch 6/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 6/100: 100%|██████████| 1/1 [00:00<00:00, 174.82it/s, loss=1.0229e+02, damping=1.0000e-04, attempts=3]
Epoch 6/100: 100%|██████████| 1/1 [00:00<00:00, 119.74it/s, epoch_avg_loss=1.0229e+02]

Epoch 7/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 7/100: 100%|██████████| 1/1 [00:00<00:00, 159.19it/s, loss=9.2458e+01, damping=1.0000e-04, attempts=2]
Epoch 7/100: 100%|██████████| 1/1 [00:00<00:00, 119.10it/s, epoch_avg_loss=9.2458e+01]

Epoch 8/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 8/100: 100%|██████████| 1/1 [00:00<00:00, 133.09it/s, loss=9.2027e+01, damping=1.0000e-01, attempts=5]
Epoch 8/100: 100%|██████████| 1/1 [00:00<00:00, 107.47it/s, epoch_avg_loss=9.2027e+01]

Epoch 9/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 9/100: 100%|██████████| 1/1 [00:00<00:00, 191.88it/s, loss=7.6824e+01, damping=1.0000e-02, attempts=1]
Epoch 9/100: 100%|██████████| 1/1 [00:00<00:00, 136.18it/s, epoch_avg_loss=7.6824e+01]

Epoch 10/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 10/100: 100%|██████████| 1/1 [00:00<00:00, 135.75it/s, loss=7.4756e+01, damping=1.0000e-01, attempts=3]
Epoch 10/100: 100%|██████████| 1/1 [00:00<00:00, 96.63it/s, epoch_avg_loss=7.4756e+01]

Epoch 11/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 11/100: 100%|██████████| 1/1 [00:00<00:00, 158.19it/s, loss=7.3997e+01, damping=1.0000e-01, attempts=2]
Epoch 11/100: 100%|██████████| 1/1 [00:00<00:00, 117.58it/s, epoch_avg_loss=7.3997e+01]

Epoch 12/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 12/100: 100%|██████████| 1/1 [00:00<00:00, 171.04it/s, loss=7.3536e+01, damping=1.0000e-02, attempts=1]
Epoch 12/100: 100%|██████████| 1/1 [00:00<00:00, 120.50it/s, epoch_avg_loss=7.3536e+01]

Epoch 13/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 13/100: 100%|██████████| 1/1 [00:00<00:00, 195.82it/s, loss=7.3357e+01, damping=1.0000e-03, attempts=1]
Epoch 13/100: 100%|██████████| 1/1 [00:00<00:00, 137.12it/s, epoch_avg_loss=7.3357e+01]

Epoch 14/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 14/100: 100%|██████████| 1/1 [00:00<00:00, 200.54it/s, loss=7.3342e+01, damping=1.0000e-04, attempts=1]
Epoch 14/100: 100%|██████████| 1/1 [00:00<00:00, 140.00it/s, epoch_avg_loss=7.3342e+01]

Epoch 15/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 15/100: 100%|██████████| 1/1 [00:00<00:00, 158.30it/s, loss=7.3340e+01, damping=1.0000e-03, attempts=3]
Epoch 15/100: 100%|██████████| 1/1 [00:00<00:00, 119.41it/s, epoch_avg_loss=7.3340e+01]

Epoch 16/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 16/100: 100%|██████████| 1/1 [00:00<00:00, 218.99it/s, loss=7.3333e+01, damping=1.0000e-04, attempts=1]
Epoch 16/100: 100%|██████████| 1/1 [00:00<00:00, 131.50it/s, epoch_avg_loss=7.3333e+01]

Epoch 17/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 17/100: 100%|██████████| 1/1 [00:00<00:00, 165.62it/s, loss=7.3325e+01, damping=1.0000e-05, attempts=1]
Epoch 17/100: 100%|██████████| 1/1 [00:00<00:00, 123.10it/s, epoch_avg_loss=7.3325e+01]

Epoch 18/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 18/100: 100%|██████████| 1/1 [00:00<00:00, 128.81it/s, loss=7.3316e+01, damping=1.0000e-02, attempts=5]
Epoch 18/100: 100%|██████████| 1/1 [00:00<00:00, 100.33it/s, epoch_avg_loss=7.3316e+01]

Epoch 19/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 19/100: 100%|██████████| 1/1 [00:00<00:00, 162.19it/s, loss=7.3309e+01, damping=1.0000e-02, attempts=2]
Epoch 19/100: 100%|██████████| 1/1 [00:00<00:00, 121.46it/s, epoch_avg_loss=7.3309e+01]

Epoch 20/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 20/100: 100%|██████████| 1/1 [00:00<00:00, 171.88it/s, loss=7.3303e+01, damping=1.0000e-02, attempts=2]
Epoch 20/100: 100%|██████████| 1/1 [00:00<00:00, 129.55it/s, epoch_avg_loss=7.3303e+01]

Epoch 21/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 21/100: 100%|██████████| 1/1 [00:00<00:00, 179.03it/s, loss=7.3302e+01, damping=1.0000e-03, attempts=1]
Epoch 21/100: 100%|██████████| 1/1 [00:00<00:00, 119.16it/s, epoch_avg_loss=7.3302e+01]

Epoch 22/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 22/100: 100%|██████████| 1/1 [00:00<00:00, 170.90it/s, loss=7.3292e+01, damping=1.0000e-04, attempts=1]
Epoch 22/100: 100%|██████████| 1/1 [00:00<00:00, 119.75it/s, epoch_avg_loss=7.3292e+01]

Epoch 23/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 23/100: 100%|██████████| 1/1 [00:00<00:00, 129.83it/s, loss=7.3204e+01, damping=1.0000e-03, attempts=3]
Epoch 23/100: 100%|██████████| 1/1 [00:00<00:00, 105.31it/s, epoch_avg_loss=7.3204e+01]

Epoch 24/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 24/100: 100%|██████████| 1/1 [00:00<00:00, 163.44it/s, loss=7.3198e+01, damping=1.0000e-02, attempts=3]
Epoch 24/100: 100%|██████████| 1/1 [00:00<00:00, 116.98it/s, epoch_avg_loss=7.3198e+01]

Epoch 25/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 25/100: 100%|██████████| 1/1 [00:00<00:00, 185.76it/s, loss=7.3100e+01, damping=1.0000e-03, attempts=1]
Epoch 25/100: 100%|██████████| 1/1 [00:00<00:00, 129.73it/s, epoch_avg_loss=7.3100e+01]

Epoch 26/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 26/100: 100%|██████████| 1/1 [00:00<00:00, 167.59it/s, loss=7.2892e+01, damping=1.0000e-03, attempts=2]
Epoch 26/100: 100%|██████████| 1/1 [00:00<00:00, 118.67it/s, epoch_avg_loss=7.2892e+01]

Epoch 27/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 27/100: 100%|██████████| 1/1 [00:00<00:00, 155.62it/s, loss=7.2757e+01, damping=1.0000e-02, attempts=3]
Epoch 27/100: 100%|██████████| 1/1 [00:00<00:00, 118.80it/s, epoch_avg_loss=7.2757e+01]

Epoch 28/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 28/100: 100%|██████████| 1/1 [00:00<00:00, 177.24it/s, loss=7.2671e+01, damping=1.0000e-03, attempts=1]
Epoch 28/100: 100%|██████████| 1/1 [00:00<00:00, 116.44it/s, epoch_avg_loss=7.2671e+01]

Epoch 29/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 29/100: 100%|██████████| 1/1 [00:00<00:00, 174.04it/s, loss=7.2641e+01, damping=1.0000e-03, attempts=2]
Epoch 29/100: 100%|██████████| 1/1 [00:00<00:00, 121.16it/s, epoch_avg_loss=7.2641e+01]

Epoch 30/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 30/100: 100%|██████████| 1/1 [00:00<00:00, 179.74it/s, loss=7.2605e+01, damping=1.0000e-03, attempts=2]
Epoch 30/100: 100%|██████████| 1/1 [00:00<00:00, 131.31it/s, epoch_avg_loss=7.2605e+01]

Epoch 31/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 31/100: 100%|██████████| 1/1 [00:00<00:00, 170.21it/s, loss=7.2604e+01, damping=1.0000e-03, attempts=2]
Epoch 31/100: 100%|██████████| 1/1 [00:00<00:00, 122.72it/s, epoch_avg_loss=7.2604e+01]

Epoch 32/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 32/100: 100%|██████████| 1/1 [00:00<00:00, 166.30it/s, loss=7.2603e+01, damping=1.0000e-03, attempts=2]
Epoch 32/100: 100%|██████████| 1/1 [00:00<00:00, 115.48it/s, epoch_avg_loss=7.2603e+01]

Epoch 33/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 33/100: 100%|██████████| 1/1 [00:00<00:00, 164.15it/s, loss=7.2603e+01, damping=1.0000e-03, attempts=2]
Epoch 33/100: 100%|██████████| 1/1 [00:00<00:00, 120.45it/s, epoch_avg_loss=7.2603e+01]

Epoch 34/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 34/100: 100%|██████████| 1/1 [00:00<00:00, 201.26it/s, loss=7.2598e+01, damping=1.0000e-04, attempts=1]
Epoch 34/100: 100%|██████████| 1/1 [00:00<00:00, 142.74it/s, epoch_avg_loss=7.2598e+01]

Epoch 35/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 35/100: 100%|██████████| 1/1 [00:00<00:00, 151.85it/s, loss=7.2574e+01, damping=1.0000e-02, attempts=4]
Epoch 35/100: 100%|██████████| 1/1 [00:00<00:00, 113.95it/s, epoch_avg_loss=7.2574e+01]

Epoch 36/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 36/100: 100%|██████████| 1/1 [00:00<00:00, 157.86it/s, loss=7.2437e+01, damping=1.0000e-02, attempts=2]
Epoch 36/100: 100%|██████████| 1/1 [00:00<00:00, 110.14it/s, epoch_avg_loss=7.2437e+01]

Epoch 37/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 37/100: 100%|██████████| 1/1 [00:00<00:00, 160.74it/s, loss=7.1722e+01, damping=1.0000e-02, attempts=2]
Epoch 37/100: 100%|██████████| 1/1 [00:00<00:00, 121.96it/s, epoch_avg_loss=7.1722e+01]

Epoch 38/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 38/100: 100%|██████████| 1/1 [00:00<00:00, 175.33it/s, loss=7.1482e+01, damping=1.0000e-03, attempts=1]
Epoch 38/100: 100%|██████████| 1/1 [00:00<00:00, 131.59it/s, epoch_avg_loss=7.1482e+01]

Epoch 39/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 39/100: 100%|██████████| 1/1 [00:00<00:00, 166.30it/s, loss=7.1478e+01, damping=1.0000e-03, attempts=2]
Epoch 39/100: 100%|██████████| 1/1 [00:00<00:00, 123.98it/s, epoch_avg_loss=7.1478e+01]

Epoch 40/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 40/100: 100%|██████████| 1/1 [00:00<00:00, 157.55it/s, loss=7.1478e+01, damping=1.0000e-03, attempts=2]
Epoch 40/100: 100%|██████████| 1/1 [00:00<00:00, 120.61it/s, epoch_avg_loss=7.1478e+01]

Epoch 41/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 41/100: 100%|██████████| 1/1 [00:00<00:00, 167.19it/s, loss=7.1477e+01, damping=1.0000e-03, attempts=2]
Epoch 41/100: 100%|██████████| 1/1 [00:00<00:00, 121.70it/s, epoch_avg_loss=7.1477e+01]

Epoch 42/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 42/100: 100%|██████████| 1/1 [00:00<00:00, 167.40it/s, loss=7.1477e+01, damping=1.0000e-03, attempts=2]
Epoch 42/100: 100%|██████████| 1/1 [00:00<00:00, 119.23it/s, epoch_avg_loss=7.1477e+01]

Epoch 43/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 43/100: 100%|██████████| 1/1 [00:00<00:00, 171.57it/s, loss=7.1477e+01, damping=1.0000e-03, attempts=2]
Epoch 43/100: 100%|██████████| 1/1 [00:00<00:00, 127.97it/s, epoch_avg_loss=7.1477e+01]

Epoch 44/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 44/100: 100%|██████████| 1/1 [00:00<00:00, 165.84it/s, loss=7.1477e+01, damping=1.0000e-03, attempts=2]
Epoch 44/100: 100%|██████████| 1/1 [00:00<00:00, 126.89it/s, epoch_avg_loss=7.1477e+01]

Epoch 45/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 45/100: 100%|██████████| 1/1 [00:00<00:00, 160.86it/s, loss=7.1477e+01, damping=1.0000e-03, attempts=2]
Epoch 45/100: 100%|██████████| 1/1 [00:00<00:00, 113.62it/s, epoch_avg_loss=7.1477e+01]

Epoch 46/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 46/100: 100%|██████████| 1/1 [00:00<00:00, 165.47it/s, loss=7.1477e+01, damping=1.0000e-03, attempts=2]
Epoch 46/100: 100%|██████████| 1/1 [00:00<00:00, 114.42it/s, epoch_avg_loss=7.1477e+01]

Epoch 47/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 47/100: 100%|██████████| 1/1 [00:00<00:00, 168.55it/s, loss=7.1477e+01, damping=1.0000e-03, attempts=2]
Epoch 47/100: 100%|██████████| 1/1 [00:00<00:00, 124.29it/s, epoch_avg_loss=7.1477e+01]

Epoch 48/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 48/100: 100%|██████████| 1/1 [00:00<00:00, 178.13it/s, loss=7.1477e+01, damping=1.0000e-03, attempts=2]
Epoch 48/100: 100%|██████████| 1/1 [00:00<00:00, 133.95it/s, epoch_avg_loss=7.1477e+01]

Epoch 49/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 49/100: 100%|██████████| 1/1 [00:00<00:00, 194.69it/s, loss=7.1477e+01, damping=1.0000e-04, attempts=1]
Epoch 49/100: 100%|██████████| 1/1 [00:00<00:00, 146.61it/s, epoch_avg_loss=7.1477e+01]

Epoch 50/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 50/100: 100%|██████████| 1/1 [00:00<00:00, 166.01it/s, loss=7.1476e+01, damping=1.0000e-03, attempts=3]
Epoch 50/100: 100%|██████████| 1/1 [00:00<00:00, 129.23it/s, epoch_avg_loss=7.1476e+01]

Epoch 51/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 51/100: 100%|██████████| 1/1 [00:00<00:00, 172.53it/s, loss=7.1475e+01, damping=1.0000e-03, attempts=2]
Epoch 51/100: 100%|██████████| 1/1 [00:00<00:00, 117.18it/s, epoch_avg_loss=7.1475e+01]

Epoch 52/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 52/100: 100%|██████████| 1/1 [00:00<00:00, 156.53it/s, loss=7.1474e+01, damping=1.0000e-03, attempts=2]
Epoch 52/100: 100%|██████████| 1/1 [00:00<00:00, 101.63it/s, epoch_avg_loss=7.1474e+01]

Epoch 53/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 53/100: 100%|██████████| 1/1 [00:00<00:00, 154.66it/s, loss=7.1471e+01, damping=1.0000e-02, attempts=3]
Epoch 53/100: 100%|██████████| 1/1 [00:00<00:00, 107.84it/s, epoch_avg_loss=7.1471e+01]

Epoch 54/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 54/100: 100%|██████████| 1/1 [00:00<00:00, 174.82it/s, loss=7.1468e+01, damping=1.0000e-02, attempts=2]
Epoch 54/100: 100%|██████████| 1/1 [00:00<00:00, 115.38it/s, epoch_avg_loss=7.1468e+01]

Epoch 55/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 55/100: 100%|██████████| 1/1 [00:00<00:00, 162.67it/s, loss=7.0116e+01, damping=1.0000e-03, attempts=1]
Epoch 55/100: 100%|██████████| 1/1 [00:00<00:00, 119.40it/s, epoch_avg_loss=7.0116e+01]

Epoch 56/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 56/100: 100%|██████████| 1/1 [00:00<00:00, 125.07it/s, loss=6.8539e+01, damping=1.0000e+00, attempts=5]
Epoch 56/100: 100%|██████████| 1/1 [00:00<00:00, 91.21it/s, epoch_avg_loss=6.8539e+01]

Epoch 57/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 57/100: 100%|██████████| 1/1 [00:00<00:00, 152.43it/s, loss=6.2031e+01, damping=1.0000e+00, attempts=2]
Epoch 57/100: 100%|██████████| 1/1 [00:00<00:00, 111.66it/s, epoch_avg_loss=6.2031e+01]

Epoch 58/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 58/100: 100%|██████████| 1/1 [00:00<00:00, 183.05it/s, loss=5.6254e+01, damping=1.0000e-01, attempts=1]
Epoch 58/100: 100%|██████████| 1/1 [00:00<00:00, 130.08it/s, epoch_avg_loss=5.6254e+01]

Epoch 59/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 59/100: 100%|██████████| 1/1 [00:00<00:00, 174.31it/s, loss=3.2908e+01, damping=1.0000e-02, attempts=1]
Epoch 59/100: 100%|██████████| 1/1 [00:00<00:00, 132.89it/s, epoch_avg_loss=3.2908e+01]

Epoch 60/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 60/100: 100%|██████████| 1/1 [00:00<00:00, 157.84it/s, loss=3.2109e+01, damping=1.0000e-01, attempts=3]
Epoch 60/100: 100%|██████████| 1/1 [00:00<00:00, 117.87it/s, epoch_avg_loss=3.2109e+01]

Epoch 61/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 61/100: 100%|██████████| 1/1 [00:00<00:00, 196.58it/s, loss=2.2715e+01, damping=1.0000e-02, attempts=1]
Epoch 61/100: 100%|██████████| 1/1 [00:00<00:00, 143.70it/s, epoch_avg_loss=2.2715e+01]

Epoch 62/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 62/100: 100%|██████████| 1/1 [00:00<00:00, 153.03it/s, loss=1.1334e+01, damping=1.0000e-02, attempts=2]
Epoch 62/100: 100%|██████████| 1/1 [00:00<00:00, 100.55it/s, epoch_avg_loss=1.1334e+01]

Epoch 63/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 63/100: 100%|██████████| 1/1 [00:00<00:00, 162.49it/s, loss=2.1432e+00, damping=1.0000e-02, attempts=2]
Epoch 63/100: 100%|██████████| 1/1 [00:00<00:00, 116.87it/s, epoch_avg_loss=2.1432e+00]

Epoch 64/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 64/100: 100%|██████████| 1/1 [00:00<00:00, 189.59it/s, loss=2.0849e+00, damping=1.0000e-03, attempts=1]
Epoch 64/100: 100%|██████████| 1/1 [00:00<00:00, 118.93it/s, epoch_avg_loss=2.0849e+00]

Epoch 65/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 65/100: 100%|██████████| 1/1 [00:00<00:00, 193.30it/s, loss=1.3004e+00, damping=1.0000e-04, attempts=1]
Epoch 65/100: 100%|██████████| 1/1 [00:00<00:00, 143.18it/s, epoch_avg_loss=1.3004e+00]

Epoch 66/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 66/100: 100%|██████████| 1/1 [00:00<00:00, 198.65it/s, loss=9.9273e-01, damping=1.0000e-04, attempts=2]
Epoch 66/100: 100%|██████████| 1/1 [00:00<00:00, 136.55it/s, epoch_avg_loss=9.9273e-01]

Epoch 67/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 67/100: 100%|██████████| 1/1 [00:00<00:00, 161.57it/s, loss=3.6004e-01, damping=1.0000e-04, attempts=2]
Epoch 67/100: 100%|██████████| 1/1 [00:00<00:00, 104.77it/s, epoch_avg_loss=3.6004e-01]

Epoch 68/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 68/100: 100%|██████████| 1/1 [00:00<00:00, 182.42it/s, loss=1.1268e-01, damping=1.0000e-04, attempts=2]
Epoch 68/100: 100%|██████████| 1/1 [00:00<00:00, 124.30it/s, epoch_avg_loss=1.1268e-01]

Epoch 69/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 69/100: 100%|██████████| 1/1 [00:00<00:00, 158.53it/s, loss=9.6615e-02, damping=1.0000e-04, attempts=2]
Epoch 69/100: 100%|██████████| 1/1 [00:00<00:00, 109.16it/s, epoch_avg_loss=9.6615e-02]

Epoch 70/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 70/100: 100%|██████████| 1/1 [00:00<00:00, 156.05it/s, loss=8.8501e-02, damping=1.0000e-04, attempts=2]
Epoch 70/100: 100%|██████████| 1/1 [00:00<00:00, 109.23it/s, epoch_avg_loss=8.8501e-02]

Epoch 71/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 71/100: 100%|██████████| 1/1 [00:00<00:00, 151.93it/s, loss=8.0343e-02, damping=1.0000e-05, attempts=1]
Epoch 71/100: 100%|██████████| 1/1 [00:00<00:00, 109.90it/s, epoch_avg_loss=8.0343e-02]

Epoch 72/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 72/100: 100%|██████████| 1/1 [00:00<00:00, 143.10it/s, loss=7.9880e-02, damping=1.0000e-04, attempts=3]
Epoch 72/100: 100%|██████████| 1/1 [00:00<00:00, 108.78it/s, epoch_avg_loss=7.9880e-02]

Epoch 73/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 73/100: 100%|██████████| 1/1 [00:00<00:00, 162.68it/s, loss=7.9830e-02, damping=1.0000e-04, attempts=2]
Epoch 73/100: 100%|██████████| 1/1 [00:00<00:00, 120.88it/s, epoch_avg_loss=7.9830e-02]

Epoch 74/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 74/100: 100%|██████████| 1/1 [00:00<00:00, 152.86it/s, loss=7.9729e-02, damping=1.0000e-04, attempts=2]
Epoch 74/100: 100%|██████████| 1/1 [00:00<00:00, 118.26it/s, epoch_avg_loss=7.9729e-02]

Epoch 75/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 75/100: 100%|██████████| 1/1 [00:00<00:00, 164.81it/s, loss=7.9718e-02, damping=1.0000e-04, attempts=2]
Epoch 75/100: 100%|██████████| 1/1 [00:00<00:00, 113.24it/s, epoch_avg_loss=7.9718e-02]

Epoch 76/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 76/100: 100%|██████████| 1/1 [00:00<00:00, 153.80it/s, loss=7.8828e-02, damping=1.0000e-03, attempts=3]
Epoch 76/100: 100%|██████████| 1/1 [00:00<00:00, 109.91it/s, epoch_avg_loss=7.8828e-02]

Epoch 77/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 77/100: 100%|██████████| 1/1 [00:00<00:00, 159.53it/s, loss=7.8009e-02, damping=1.0000e-03, attempts=2]
Epoch 77/100: 100%|██████████| 1/1 [00:00<00:00, 107.67it/s, epoch_avg_loss=7.8009e-02]

Epoch 78/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 78/100: 100%|██████████| 1/1 [00:00<00:00, 165.64it/s, loss=7.5008e-02, damping=1.0000e-03, attempts=2]
Epoch 78/100: 100%|██████████| 1/1 [00:00<00:00, 121.74it/s, epoch_avg_loss=7.5008e-02]

Epoch 79/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 79/100: 100%|██████████| 1/1 [00:00<00:00, 180.66it/s, loss=4.5072e-02, damping=1.0000e-03, attempts=2]
Epoch 79/100: 100%|██████████| 1/1 [00:00<00:00, 120.92it/s, epoch_avg_loss=4.5072e-02]

Epoch 80/100:   0%|          | 0/1 [00:00<?, ?it/s]
Epoch 80/100: 100%|██████████| 1/1 [00:00<00:00, 156.59it/s, loss=1.8710e-02, damping=1.0000e-02, attempts=3]

Training complete. Final epoch average loss: 1.1360e-28

In [34]:
with torch.no_grad():

    P_raw = model_P(Xv).numpy().ravel()
    N_raw = model_N(Xv).numpy().ravel()
    A_raw = model_A(Xv).numpy().ravel()

total = P_raw + N_raw + A_raw

P = 100 * P_raw / total
N = 100 * N_raw / total
A = 100 * A_raw / total

pred = np.column_stack([P, N, A])

In [35]:
result = pd.DataFrame({
    "Sample": val["Sample No."].values,
    "P_exp": y_val["P"].values,
    "P_pred": P,
    "N_exp": y_val["N"].values,
    "N_pred": N,
    "A_exp": y_val["A"].values,
    "A_pred": A,
})

display(result.round(2))

   Sample  P_exp  P_pred  N_exp  N_pred  A_exp  A_pred
0      17   15.8   14.15   35.9   36.84   48.3   49.01
1      18   14.4   15.28   23.3   20.29   62.2   64.43
2      19    4.9    5.04   21.1   22.93   74.0   72.03
3      20   10.9   44.12   29.9   34.36   59.2   21.51
4      21   10.4    8.86   18.5    5.27   71.0   85.87
5      22    6.3   10.00   26.2   24.88   67.5   65.12

In [36]:
obs = y_val[["P", "N", "A"]].to_numpy().ravel()
prd = pred.ravel()

rmse = np.sqrt(
    np.mean((obs - prd)**2)
)

sse = np.sum((obs - prd)**2)
sst = np.sum((obs - obs.mean())**2)

r2 = 1 - sse / sst

print(f"RMSE = {rmse:.3f}")
print(f"R²   = {r2:.4f}")

RMSE = 12.888
R²   = 0.6930

In [37]:
def predict_pna(X):
    with torch.no_grad():
        p = model_P(X).numpy().ravel()
        n = model_N(X).numpy().ravel()
        a = model_A(X).numpy().ravel()

    s = p + n + a

    return np.column_stack([
        100*p/s,
        100*n/s,
        100*a/s
    ])

def evaluate(name, X, y):
    p = predict_pna(X)
    o = y[["P", "N", "A"]].to_numpy()

    rmse = np.sqrt(
        np.mean((o.ravel() - p.ravel())**2)
    )

    sse = np.sum((o.ravel() - p.ravel())**2)
    sst = np.sum(
        (o.ravel() - o.ravel().mean())**2
    )

    r2 = 1 - sse/sst

    print(
        f"{name:12s} RMSE = {rmse:.3f}   "
        f"R² = {r2:.4f}"
    )

evaluate("TRAIN", Xtr, y_train)
evaluate("TEST", Xte, y_test)
evaluate("VALIDATION", Xv, y_val)

TRAIN        RMSE = 0.089   R² = 1.0000
TEST         RMSE = 14.348   R² = 0.4706
VALIDATION   RMSE = 12.888   R² = 0.6930